version: "3.8"

services:

  api:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    command:
      - uvicorn
      - app:init
      - --host 0.0.0.0
      - --port 8000
    ports:
      - "80:80"