# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - W37L-ML-Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6898d6d9c9e84bfab13f5fa4361d19cc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ff4a4a4dfb47434695d81a82d1d2930c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_6898d6d9c9e84bfab13f5fa4361d19cc }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'W37L-ML-Services'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_65139e2b6be94f6e813bcf4c5060f1b7 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_6898d6d9c9e84bfab13f5fa4361d19cc }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'