name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - 'development/**'
  pull_request:
    branches:
      - development
      - 'development/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment (Python 3.11.7)
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest tests
          
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d
        
      - name: Build Docker image
        run: docker build -t python-app-image .

      - name: Build and Run Containers
        run: |
          docker-compose -f docker-compose.yml up --build -d
        working-directory: ./

      - name: Stop and remove Docker Compose services
        run: docker-compose -f docker-compose.yml down

